FROM oven/bun:latest
RUN apt-get update -y && apt-get install -y openssl
RUN apt-get update && apt-get install -y nodejs npm && rm -rf /var/lib/apt/lists/*


WORKDIR /usr/src/app

COPY ./packages ./packages
COPY ./bun.lock ./bun.lock

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/web ./apps/web

RUN bun i 
RUN bun run db:generate
RUN bun run build

EXPOSE 3000

CMD [ "bun", "run", "web:start" ]