FROM oven/bun:latest
RUN apt-get update -y && apt-get install -y openssl
RUN apt-get update && apt-get install -y nodejs npm && rm -rf /var/lib/apt/lists/*


WORKDIR /usr/src/app

COPY . .

RUN bun i 
RUN bun run db:generate
RUN bun run build

EXPOSE 3000

CMD [ "bun", "run", "web:start" ]