FROM oven/bun:latest

RUN apt-get update -y && apt-get install -y openssl
RUN apt-get update && apt-get install -y nodejs npm && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app

COPY . .

RUN bun i --verbose

# Generate Prisma client in generated/client
RUN cd packages/db && bunx prisma generate

CMD [ "bun", "run", "docker:start" ]