version: "3.8"

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: sih
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      dockerfile: ./docker/dev/dockerfile.fe
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/sih
      JWT_SECRET: your_jwt_secret
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    command: ["bun", "run", "docker:start"]

volumes:
  db_data:
