FROM oven/bun:latest
RUN apt-get update -y && apt-get install -y openssl

ARG DATABASE_URL
WORKDIR /usr/src/app

COPY ./packages ./packages
COPY ./bun.lock ./bun.lock

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps.web ./apps/web

RUN bun i 
RUN bun run db:generate
ENV DATABASE_URL=${DATABASE_URL}
RUN bun run build

EXPOSE 3000

CMD [ "bun", "run", "start:web" ]